<?php
return [
'data'=>[
    "acct_no" => "acct_no",
    "claim_no" => "claim_no",
    "patient_name" => "patient_name",
    "dos" => "dos",
    "dob" => "dob",
    "ssn" => "ssn",
    "gender" => "gender",
    "phone_no" => "phone_no",
    "address_line_1" => "address_line_1",
    "address_line_2" => "address_line_2",
    "city" => "city",
    "state" => "state",
    "zipcode" => "zipcode",
    "gurantor_name" => "guarantor",
    "employer_name" => "employer",
    "responsibility" => "responsibility",
    "insurance_type" => "insurance_type",
    "primary_insurance_name" => "primary_insurance_name",
    "primary_policy_id" => "primary_policy_id",
    "primary_group_id" => "primary_group_id",
    "primary_insurance_address_line_1" => "primary_insurance_address_line_1",
    "primary_insurance_address_line_2" => "primary_insurance_address_line_2",
    "primary_insurance_city" => "primary_insurance_city",
    "primary_insurance_state" => "primary_insurance_state",
    "primary_insurance_zipcode" => "primary_insurance_zipcode",
    "secondary_insurance_name" => "secondary_insurance_name",
    "secondary_policy_id" => "secondary_policy_id",
    "secondary_group_id" => "secondary_group_id",
    "secondary_insurance_address_line_1" => "secondary_insurance_address_line_1",
    "secondary_insurance_address_line_2" => "secondary_insurance_address_line_2",
    "secondary_insurance_city" => "secondary_insurance_city",
    "secondary_insurance_state" => "secondary_insurance_state",
    "secondary_insurance_zipcode" => "secondary_insurance_zipcode",
    "tertiary_insurance_name" => "tertiary_insurance_name",
    "tertiary_policy_id" => "tertiary_policy_id",
    "tertiary_group_id" => "tertiary_group_id",
    "tertiary_insurance_address_line_1" => "tertiary_insurance_address_line_1",
    "tertiary_insurance_address_line_2" => "tertiary_insurance_address_line_2",
    "tertiary_insurance_city" => "tertiary_insurance_city",
    "tertiary_insurance_state" => "tertiary_insurance_state",
    "tertiary_insurance_zipcode" => "tertiary_insurance_zipcode",
    "authorization" => "authorization",
    "rendering_provider" => "rendering_provider",
    "billing_provider" => "billing_provider",
    "facility" => "facility",
    "admit_date" => "admit_date",
    "discharge_date" => "discharge_date",
    "cpt" => "cpt",
    "icd" => "icd",
    "modifier" => "modifiers",
    "units" => "units",
    "total_charges" => "total_charges",
    "pat_ar" => "pat_ar",
    "ins_ar" => "ins_ar",
    "total_ar_due" => "total_ar",
    "claim_status" => "claim_Status",
    "claim_note" => "claim_note",
    "billedlast_submit_date" => "billedlast_submit_date",
    "denial_code" => "denial_code"

]

];
?>