<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubParametersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sub_parameters')->delete();

        DB::table('sub_parameters')->insert(array(
            0 => array(
                'id' => 1,
                'parent_id' => 1,
                'sub_parameter' => 'Previous history not reviewed',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            1 => array(
                'id' => 2,
                'parent_id' => 1,
                'sub_parameter' => 'Website details not reviewed',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            2 => array(
                'id' => 3,
                'parent_id' => 1,
                'sub_parameter' => 'EOB not reviewed',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            3 => array(
                'id' => 4,
                'parent_id' => 1,
                'sub_parameter' => 'SOP Not followed',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            4 => array(
                'id' => 5,
                'parent_id' => 1,
                'sub_parameter' => 'Missed to call the correct payer',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            5 => array(
                'id' => 6,
                'parent_id' => 1,
                'sub_parameter' => 'Missed to check denial/payment details',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            6 => array(
                'id' => 7,
                'parent_id' => 1,
                'sub_parameter' => 'Missed to check additional systems - clearing house etc.',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            7 => array(
                'id' => 8,
                'parent_id' => 2,
                'sub_parameter' => 'User called outside the business hours',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            8 => array(
                'id' => 9,
                'parent_id' => 2,
                'sub_parameter' => 'Missed to obtain all the denial /Payment details',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            9 => array(
                'id' => 10,
                'parent_id' => 2,
                'sub_parameter' => 'Call recording not found in system or any proof',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            10 => array(
                'id' => 11,
                'parent_id' => 2,
                'sub_parameter' => 'Missed to obtain , what addi information required',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            11 => array(
                'id' => 12,
                'parent_id' => 2,
                'sub_parameter' => 'Missed to obtain the submission /resubmission deta',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            12 => array(
                'id' => 13,
                'parent_id' => 2,
                'sub_parameter' => 'Voice mail protocol not followed',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            13 => array(
                'id' => 14,
                'parent_id' => 3,
                'sub_parameter' => 'Missed to update notes in software',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            14 => array(
                'id' => 15,
                'parent_id' => 3,
                'sub_parameter' => 'Information obtained does not match the scenario',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            15 => array(
                'id' => 16,
                'parent_id' => 3,
                'sub_parameter' => 'Missed to document the end action in notes',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            16 => array(
                'id' => 17,
                'parent_id' => 3,
                'sub_parameter' => 'incorrect notes updated in the software',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            17 => array(
                'id' => 18,
                'parent_id' => 3,
                'sub_parameter' => 'Missed to update the status /kick/action code',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            18 => array(
                'id' => 19,
                'parent_id' => 4,
                'sub_parameter' => 'Missed to take action on the account',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            19 => array(
                'id' => 20,
                'parent_id' => 4,
                'sub_parameter' => 'Missed to update the log /appeal',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            20 => array(
                'id' => 21,
                'parent_id' => 4,
                'sub_parameter' => 'Incorrect action taken on the account',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            21 => array(
                'id' => 22,
                'parent_id' => 4,
                'sub_parameter' => 'Missed to follow up on the account',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            22 => array(
                'id' => 23,
                'parent_id' => 4,
                'sub_parameter' => 'Missed to update correct details in software',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            23 => array(
                'id' => 24,
                'parent_id' => 5,
                'sub_parameter' => 'User in Ramp',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            24 => array(
                'id' => 25,
                'parent_id' => 5,
                'sub_parameter' => 'It does not impact the end action /outcome',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
            25 => array(
                'id' => 26,
                'parent_id' => 6,
                'sub_parameter' => 'User failed to re-work on the account  (48 hours expired)',
                'status' => 1,
                'created_by' => 15,
                'updated_by' => NULL,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
        ));
    }
}
